Add set value command.
Dawgma-1712/FRC-2019 pull request #12
Opened 2019-01-24 21:49 UTC by connor-marsh

Which sets the solenoid to forward (collapsed) or reverse (not collapsed) depending on what the input from the command is.

2019-01-26 19:50 UTC, cecer1712 requested changes
There is a broken wire in Template for Hatch Intake Immediate with Deadband, two clusters are connected incorrectly

2019-01-29 15:28 UTC, redbow-kimee approved these changes
same as @cecer1712 once that's fixed and she's okay with it she can merge.

2019-02-07 23:20 UTC, redbow-kimee requested changes
Unique talon numbers.

2019-02-09 19:37 UTC, redbow-kimee approved these changes

2019-02-09 19:50 UTC, cecer1712 approved these changes

2019-02-09 19:52 UTC, merged