Create two talonSRXs and slave two victorSPXs to each. The configurat…
Dawgma-1712/FRC-2019 pull request #2
Opened 2019-01-12 19:38 UTC by cecer1712

…ions have yet to be tested and decided for each talon. Code has yet to be tested.

2019-02-01 06:09 UTC, RedBow commented
1. Enhanced Motor Controller Configurable is placed twice on front panel. They look identical, so does it make sense to have a single one fed to both sides? will there be side based configuration to come?
2. are device numbers made unique by motor controller type? looks like theres a 1, 2 Talon and a 1, 2, 3, 4 Victor. a little concerned about the duplication.
3. does drive train need a set reference (arrow to hashtag). if its only ever used within the Drive Controller it shouldn't need one as only the drive controller should use it.

2019-02-01 06:10 UTC, redbow-kimee requested changes
see previous comment

2019-02-02 21:01 UTC, cecer1712 commented
The configurable was branched to both talons.  Victor numbers 1 and 2 were changed to 5 and 6. The drive train set reference was deleted.

2019-02-02 21:02 UTC, redbow-kimee approved these changes

2019-02-02 21:29 UTC, nikolasm2000 approved these changes

2019-02-07 22:57 UTC, merged